name: atendimento_automatico
description: Aplicação desenvolvida para Projeto Integrador II - T21.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  font_awesome_flutter: ^10.4.0
  carousel_slider: ^4.2.1
  url_launcher: ^6.1.10
  dartz: ^0.10.1
  get_it: ^7.3.0
  hasura_connect: ^4.0.0+4
  image_picker: ^0.8.7+1
  path_provider: ^2.0.14
  intl: ^0.18.1
  scoped_model: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: #flutter pub run flutter_native_splash:create

flutter:
  uses-material-design: true
  assets:
    - assets/images/
